version: '3.8'
services:
  database:
    image: postgres:15-alpine
    volumes:
      - db:/data/postgres
    ports:
      - 5433:5432
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s

  cache:
    image: redis:6.2-alpine
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
    ports:
      - 6377:6379  

networks:
  db:
    driver: bridge

volumes:
  db:
  cache: